using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BusinessObjects.Common
{
    public class TempTableObject : BusinessObject<TempTableObject>
    {
        public int UserMasterId { get; set; }

        public DateTime DATE1 { get; set; }
        public DateTime DATE2 { get; set; }
        public DateTime DATE3 { get; set; }
        public DateTime DATE4 { get; set; }
        public DateTime DATE5 { get; set; }
        public DateTime DATE6 { get; set; }
        public DateTime DATE7 { get; set; }
        public DateTime DATE8 { get; set; }
        public DateTime DATE9 { get; set; }
        public DateTime DATE10 { get; set; }
        public DateTime DATE11 { get; set; }
        public DateTime DATE12 { get; set; }
        public DateTime DATE13 { get; set; }
        public DateTime DATE14 { get; set; }
        public DateTime DATE15 { get; set; }
        public DateTime DATE16 { get; set; }
        public DateTime DATE17 { get; set; }
        public DateTime DATE18 { get; set; }
        public DateTime DATE19 { get; set; }
        public DateTime DATE20 { get; set; }

        public string DESC1 { get; set; }
        public string DESC2 { get; set; }
        public string DESC3 { get; set; }
        public string DESC4 { get; set; }
        public string DESC5 { get; set; }
        public string DESC6 { get; set; }
        public string DESC7 { get; set; }
        public string DESC8 { get; set; }
        public string DESC9 { get; set; }
        public string DESC10 { get; set; }
        public string DESC11 { get; set; }
        public string DESC12 { get; set; }
        public string DESC13 { get; set; }
        public string DESC14 { get; set; }
        public string DESC15 { get; set; }
        public string DESC16 { get; set; }
        public string DESC17 { get; set; }
        public string DESC18 { get; set; }
        public string DESC19 { get; set; }
        public string DESC20 { get; set; }
        public string DESC21 { get; set; }
        public string DESC22 { get; set; }
        public string DESC23 { get; set; }
        public string DESC24 { get; set; }
        public string DESC25 { get; set; }
        public string DESC26 { get; set; }
        public string DESC27 { get; set; }
        public string DESC28 { get; set; }
        public string DESC29 { get; set; }
        public string DESC30 { get; set; }
        public string DESC31 { get; set; }
        public string DESC32 { get; set; }
        public string DESC33 { get; set; }
        public string DESC34 { get; set; }
        public string DESC35 { get; set; }
        public string DESC36 { get; set; }
        public string DESC37 { get; set; }
        public string DESC38 { get; set; }
        public string DESC39 { get; set; }
        public string DESC40 { get; set; }
        public string DESC41 { get; set; }
        public string DESC42 { get; set; }
        public string DESC43 { get; set; }
        public string DESC44 { get; set; }
        public string DESC45 { get; set; }
        public string DESC46 { get; set; }
        public string DESC47 { get; set; }
        public string DESC48 { get; set; }
        public string DESC49 { get; set; }
        public string DESC50 { get; set; }
        public string DESC51 { get; set; }
        public string DESC52 { get; set; }
        public string DESC53 { get; set; }
        public string DESC54 { get; set; }
        public string DESC55 { get; set; }
        public string DESC56 { get; set; }
        public string DESC57 { get; set; }
        public string DESC58 { get; set; }
        public string DESC59 { get; set; }
        public string DESC60 { get; set; }
        public string DESC61 { get; set; }
        public string DESC62 { get; set; }
        public string DESC63 { get; set; }
        public string DESC64 { get; set; }
        public string DESC65 { get; set; }
        public string DESC66 { get; set; }
        public string DESC67 { get; set; }
        public string DESC68 { get; set; }
        public string DESC69 { get; set; }
        public string DESC70 { get; set; }
        public string DESC71 { get; set; }
        public string DESC72 { get; set; }
        public string DESC73 { get; set; }
        public string DESC74 { get; set; }
        public string DESC75 { get; set; }
        public string DESC76 { get; set; }
        public string DESC77 { get; set; }
        public string DESC78 { get; set; }
        public string DESC79 { get; set; }
        public string DESC80 { get; set; }
        public string DESC81 { get; set; }
        public string DESC82 { get; set; }
        public string DESC83 { get; set; }
        public string DESC84 { get; set; }
        public string DESC85 { get; set; }
        public string DESC86 { get; set; }
        public string DESC87 { get; set; }
        public string DESC88 { get; set; }
        public string DESC89 { get; set; }
        public string DESC90 { get; set; }
        public string DESC91 { get; set; }
        public string DESC92 { get; set; }
        public string DESC93 { get; set; }
        public string DESC94 { get; set; }
        public string DESC95 { get; set; }
        public string DESC96 { get; set; }
        public string DESC97 { get; set; }
        public string DESC98 { get; set; }
        public string DESC99 { get; set; }
        public string DESC100 { get; set; }
        public string DESC101 { get; set; }
        public string DESC102 { get; set; }
        public string DESC103 { get; set; }
        public string DESC104 { get; set; }
        public string DESC105 { get; set; }
        public string DESC106 { get; set; }
        public string DESC107 { get; set; }
        public string DESC108 { get; set; }
        public string DESC109 { get; set; }
        public string DESC110 { get; set; }
        public string DESC111 { get; set; }
        public string DESC112 { get; set; }
        public string DESC113 { get; set; }
        public string DESC114 { get; set; }
        public string DESC115 { get; set; }
        public string DESC116 { get; set; }
        public string DESC117 { get; set; }
        public string DESC118 { get; set; }
        public string DESC119 { get; set; }
        public string DESC120 { get; set; }
        public string DESC121 { get; set; }
        public string DESC122 { get; set; }
        public string DESC123 { get; set; }
        public string DESC124 { get; set; }
        public string DESC125 { get; set; }
        public string DESC126 { get; set; }
        public string DESC127 { get; set; }
        public string DESC128 { get; set; }
        public string DESC129 { get; set; }
        public string DESC130 { get; set; }
        public string DESC131 { get; set; }
        public string DESC132 { get; set; }
        public string DESC133 { get; set; }
        public string DESC134 { get; set; }
        public string DESC135 { get; set; }
        public string DESC136 { get; set; }
        public string DESC137 { get; set; }
        public string DESC138 { get; set; }
        public string DESC139 { get; set; }
        public string DESC140 { get; set; }
        public string DESC141 { get; set; }
        public string DESC142 { get; set; }
        public string DESC143 { get; set; }
        public string DESC144 { get; set; }
        public string DESC145 { get; set; }
        public string DESC146 { get; set; }
        public string DESC147 { get; set; }
        public string DESC148 { get; set; }
        public string DESC149 { get; set; }
        public string DESC150 { get; set; }
        public string DESC151 { get; set; }
        public string DESC152 { get; set; }
        public string DESC153 { get; set; }
        public string DESC154 { get; set; }
        public string DESC155 { get; set; }
        public string DESC156 { get; set; }
        public string DESC157 { get; set; }
        public string DESC158 { get; set; }
        public string DESC159 { get; set; }
        public string DESC160 { get; set; }
        public string DESC161 { get; set; }
        public string DESC162 { get; set; }
        public string DESC163 { get; set; }
        public string DESC164 { get; set; }
        public string DESC165 { get; set; }
        public string DESC166 { get; set; }
        public string DESC167 { get; set; }
        public string DESC168 { get; set; }
        public string DESC169 { get; set; }
        public string DESC170 { get; set; }
        public string DESC171 { get; set; }
        public string DESC172 { get; set; }
        public string DESC173 { get; set; }
        public string DESC174 { get; set; }
        public string DESC175 { get; set; }
        public string DESC176 { get; set; }
        public string DESC177 { get; set; }
        public string DESC178 { get; set; }
        public string DESC179 { get; set; }
        public string DESC180 { get; set; }
        public string DESC181 { get; set; }
        public string DESC182 { get; set; }
        public string DESC183 { get; set; }
        public string DESC184 { get; set; }
        public string DESC185 { get; set; }
        public string DESC186 { get; set; }
        public string DESC187 { get; set; }
        public string DESC188 { get; set; }
        public string DESC189 { get; set; }
        public string DESC190 { get; set; }
        public string DESC191 { get; set; }
        public string DESC192 { get; set; }
        public string DESC193 { get; set; }
        public string DESC194 { get; set; }
        public string DESC195 { get; set; }
        public string DESC196 { get; set; }
        public string DESC197 { get; set; }
        public string DESC198 { get; set; }
        public string DESC199 { get; set; }
        public string DESC200 { get; set; }


        public decimal AMOUNT1 { get; set; }
        public decimal AMOUNT2 { get; set; }
        public decimal AMOUNT3 { get; set; }
        public decimal AMOUNT4 { get; set; }
        public decimal AMOUNT5 { get; set; }
        public decimal AMOUNT6 { get; set; }
        public decimal AMOUNT7 { get; set; }
        public decimal AMOUNT8 { get; set; }
        public decimal AMOUNT9 { get; set; }
        public decimal AMOUNT10 { get; set; }
        public decimal AMOUNT11 { get; set; }
        public decimal AMOUNT12 { get; set; }
        public decimal AMOUNT13 { get; set; }
        public decimal AMOUNT14 { get; set; }
        public decimal AMOUNT15 { get; set; }
        public decimal AMOUNT16 { get; set; }
        public decimal AMOUNT17 { get; set; }
        public decimal AMOUNT18 { get; set; }
        public decimal AMOUNT19 { get; set; }
        public decimal AMOUNT20 { get; set; }
        public decimal AMOUNT21 { get; set; }
        public decimal AMOUNT22 { get; set; }
        public decimal AMOUNT23 { get; set; }
        public decimal AMOUNT24 { get; set; }
        public decimal AMOUNT25 { get; set; }
        public decimal AMOUNT26 { get; set; }
        public decimal AMOUNT27 { get; set; }
        public decimal AMOUNT28 { get; set; }
        public decimal AMOUNT29 { get; set; }
        public decimal AMOUNT30 { get; set; }
        public decimal AMOUNT31 { get; set; }
        public decimal AMOUNT32 { get; set; }
        public decimal AMOUNT33 { get; set; }
        public decimal AMOUNT34 { get; set; }
        public decimal AMOUNT35 { get; set; }
        public decimal AMOUNT36 { get; set; }
        public decimal AMOUNT37 { get; set; }
        public decimal AMOUNT38 { get; set; }
        public decimal AMOUNT39 { get; set; }
        public decimal AMOUNT40 { get; set; }
        public decimal AMOUNT41 { get; set; }
        public decimal AMOUNT42 { get; set; }
        public decimal AMOUNT43 { get; set; }
        public decimal AMOUNT44 { get; set; }
        public decimal AMOUNT45 { get; set; }
        public decimal AMOUNT46 { get; set; }
        public decimal AMOUNT47 { get; set; }
        public decimal AMOUNT48 { get; set; }
        public decimal AMOUNT49 { get; set; }
        public decimal AMOUNT50 { get; set; }
        public decimal AMOUNT51 { get; set; }
        public decimal AMOUNT52 { get; set; }
        public decimal AMOUNT53 { get; set; }
        public decimal AMOUNT54 { get; set; }
        public decimal AMOUNT55 { get; set; }
        public decimal AMOUNT56 { get; set; }
        public decimal AMOUNT57 { get; set; }
        public decimal AMOUNT58 { get; set; }
        public decimal AMOUNT59 { get; set; }
        public decimal AMOUNT60 { get; set; }
        public decimal AMOUNT61 { get; set; }
        public decimal AMOUNT62 { get; set; }
        public decimal AMOUNT63 { get; set; }
        public decimal AMOUNT64 { get; set; }
        public decimal AMOUNT65 { get; set; }
        public decimal AMOUNT66 { get; set; }
        public decimal AMOUNT67 { get; set; }
        public decimal AMOUNT68 { get; set; }
        public decimal AMOUNT69 { get; set; }
        public decimal AMOUNT70 { get; set; }
        public decimal AMOUNT71 { get; set; }
        public decimal AMOUNT72 { get; set; }
        public decimal AMOUNT73 { get; set; }
        public decimal AMOUNT74 { get; set; }
        public decimal AMOUNT75 { get; set; }
        public decimal AMOUNT76 { get; set; }
        public decimal AMOUNT77 { get; set; }
        public decimal AMOUNT78 { get; set; }
        public decimal AMOUNT79 { get; set; }
        public decimal AMOUNT80 { get; set; }
        public decimal AMOUNT81 { get; set; }
        public decimal AMOUNT82 { get; set; }
        public decimal AMOUNT83 { get; set; }
        public decimal AMOUNT84 { get; set; }
        public decimal AMOUNT85 { get; set; }
        public decimal AMOUNT86 { get; set; }
        public decimal AMOUNT87 { get; set; }
        public decimal AMOUNT88 { get; set; }
        public decimal AMOUNT89 { get; set; }
        public decimal AMOUNT90 { get; set; }
        public decimal AMOUNT91 { get; set; }
        public decimal AMOUNT92 { get; set; }
        public decimal AMOUNT93 { get; set; }
        public decimal AMOUNT94 { get; set; }
        public decimal AMOUNT95 { get; set; }
        public decimal AMOUNT96 { get; set; }
        public decimal AMOUNT97 { get; set; }
        public decimal AMOUNT98 { get; set; }
        public decimal AMOUNT99 { get; set; }
        public decimal AMOUNT100 { get; set; }
        public decimal AMOUNT101 { get; set; }
        public decimal AMOUNT102 { get; set; }
        public decimal AMOUNT103 { get; set; }
        public decimal AMOUNT104 { get; set; }
        public decimal AMOUNT105 { get; set; }
        public decimal AMOUNT106 { get; set; }
        public decimal AMOUNT107 { get; set; }
        public decimal AMOUNT108 { get; set; }
        public decimal AMOUNT109 { get; set; }
        public decimal AMOUNT110 { get; set; }
        public decimal AMOUNT111 { get; set; }
        public decimal AMOUNT112 { get; set; }
        public decimal AMOUNT113 { get; set; }
        public decimal AMOUNT114 { get; set; }
        public decimal AMOUNT115 { get; set; }
        public decimal AMOUNT116 { get; set; }
        public decimal AMOUNT117 { get; set; }
        public decimal AMOUNT118 { get; set; }
        public decimal AMOUNT119 { get; set; }
        public decimal AMOUNT120 { get; set; }
        public decimal AMOUNT121 { get; set; }
        public decimal AMOUNT122 { get; set; }
        public decimal AMOUNT123 { get; set; }
        public decimal AMOUNT124 { get; set; }
        public decimal AMOUNT125 { get; set; }
        public decimal AMOUNT126 { get; set; }
        public decimal AMOUNT127 { get; set; }
        public decimal AMOUNT128 { get; set; }
        public decimal AMOUNT129 { get; set; }
        public decimal AMOUNT130 { get; set; }
        public decimal AMOUNT131 { get; set; }
        public decimal AMOUNT132 { get; set; }
        public decimal AMOUNT133 { get; set; }
        public decimal AMOUNT134 { get; set; }
        public decimal AMOUNT135 { get; set; }
        public decimal AMOUNT136 { get; set; }
        public decimal AMOUNT137 { get; set; }
        public decimal AMOUNT138 { get; set; }
        public decimal AMOUNT139 { get; set; }
        public decimal AMOUNT140 { get; set; }
        public decimal AMOUNT141 { get; set; }
        public decimal AMOUNT142 { get; set; }
        public decimal AMOUNT143 { get; set; }
        public decimal AMOUNT144 { get; set; }
        public decimal AMOUNT145 { get; set; }
        public decimal AMOUNT146 { get; set; }
        public decimal AMOUNT147 { get; set; }
        public decimal AMOUNT148 { get; set; }
        public decimal AMOUNT149 { get; set; }
        public decimal AMOUNT150 { get; set; }
        public decimal AMOUNT151 { get; set; }
        public decimal AMOUNT152 { get; set; }
        public decimal AMOUNT153 { get; set; }
        public decimal AMOUNT154 { get; set; }
        public decimal AMOUNT155 { get; set; }
        public decimal AMOUNT156 { get; set; }
        public decimal AMOUNT157 { get; set; }
        public decimal AMOUNT158 { get; set; }
        public decimal AMOUNT159 { get; set; }
        public decimal AMOUNT160 { get; set; }
        public decimal AMOUNT161 { get; set; }
        public decimal AMOUNT162 { get; set; }
        public decimal AMOUNT163 { get; set; }
        public decimal AMOUNT164 { get; set; }
        public decimal AMOUNT165 { get; set; }
        public decimal AMOUNT166 { get; set; }
        public decimal AMOUNT167 { get; set; }
        public decimal AMOUNT168 { get; set; }
        public decimal AMOUNT169 { get; set; }
        public decimal AMOUNT170 { get; set; }
        public decimal AMOUNT171 { get; set; }
        public decimal AMOUNT172 { get; set; }
        public decimal AMOUNT173 { get; set; }
        public decimal AMOUNT174 { get; set; }
        public decimal AMOUNT175 { get; set; }
        public decimal AMOUNT176 { get; set; }
        public decimal AMOUNT177 { get; set; }
        public decimal AMOUNT178 { get; set; }
        public decimal AMOUNT179 { get; set; }
        public decimal AMOUNT180 { get; set; }
        public decimal AMOUNT181 { get; set; }
        public decimal AMOUNT182 { get; set; }
        public decimal AMOUNT183 { get; set; }
        public decimal AMOUNT184 { get; set; }
        public decimal AMOUNT185 { get; set; }
        public decimal AMOUNT186 { get; set; }
        public decimal AMOUNT187 { get; set; }
        public decimal AMOUNT188 { get; set; }
        public decimal AMOUNT189 { get; set; }
        public decimal AMOUNT190 { get; set; }
        public decimal AMOUNT191 { get; set; }
        public decimal AMOUNT192 { get; set; }
        public decimal AMOUNT193 { get; set; }
        public decimal AMOUNT194 { get; set; }
        public decimal AMOUNT195 { get; set; }
        public decimal AMOUNT196 { get; set; }
        public decimal AMOUNT197 { get; set; }
        public decimal AMOUNT198 { get; set; }
        public decimal AMOUNT199 { get; set; }
        public decimal AMOUNT200 { get; set; }
    }
}
